site_name: Aidar Technical Writing Portfolio

theme:
  name: material

nav:
  - Главная: index.md
  - Безопасность: security/pki-tls.md
  - Процессы (BPMN): processes/bpmn-telemetry.md
  - Промышленный код: industrial/st-code-example.md
  - REST API: api/overview.md