site_name: Айдар Ярмаков | Technical Content Engineer
site_url: https://aidar65.github.io/aidar-technical-writing/

theme:
  name: material
  language: ru
  palette:
    scheme: slate
    primary: indigo
    accent: cyan
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - tables

nav:
  - Главная: index.md
  - REST API & Integration:
      - Спецификация OpenAPI: api/openapi.md
  - Docs-as-Code & ГОСТ:
      - ТЗ на Мониторинг (ГОСТ 19.201): docs-code/tz-gost19.md
      - Архитектура C4 (Mermaid): docs-code/architecture.md
  - Промышленный домен:
      - АСУТП Затвора: industrial/valve-asutp.md
repo_name: Aidar65/aidar-technical-writing
repo_url: https://github.com/Aidar65/aidar-technical-writing
