name: Quality Gate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality-gate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@v16
        continue-on-error: true
        with:
          globs: 'docs/**/*.md'

      - name: Vale Prose Linter
        uses: errata-ai/vale-action@reviewdog
        continue-on-error: true
        with:
          files: 'docs'
          level: warning

      - name: Check Broken Links
        uses: lycheeverse/lychee-action@v1.9.0
        continue-on-error: true
        with:
          args: '--verbose --no-progress ./docs/**/*.md'
